apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gin-vue-2022-06-11t11-36-29
spec:
  encryptedData:
    .dockerconfigjson: AgBAzlcM77e+n6XBom9BAYdGWcAsXFzvRd4GOB2c18vTXW4mEZPBprLNSzWrNOWciel+lRx4UZ5JayMr8TP/jieTcRnBEJ82tb/uNTaPYFY+d7+OOFjGvh9Flqkgm+ifuACGKGwCDoz44VWeBGRjgLuv/9kwWGfCEnNpSLkLPDKOGZV0+R1Cc4BOPmsOk0gdacNVxsDd8c5eXnU6UjNfaBy+wMFO5UnoDc92gopF+0381cVy9T0HxDCfD100cgoKi3lR58FaA3Thujhi7wMaEQiSSeanWqqc7krjnGY38NCvABIV7KnuFRujlHVSmSHB0aVc/EfKqIGLNWjR+bWaBxzzaRVVBHpky4pXmZnZOVnr3y/a5EBf7wzsA+egvuMae/1bXE9UdYcpfxZk4/oEo2qmXGLmtUaExRpRu1VcxfQUwUjsvKaK9GdoNajMfa6rK3Xzwzzn/9N22O8Vn7r8/+5AGEQM62mzlx0lNVr69wO8qbjKCige2EQJzgkUa9jcD+cWoUkxUELsSsYvIpKGmo6aypKtK3EmVO8Ky/42oytdgijKT52ehmzSkOUCilvNONkTvv6855dN8Y3/tpilSJxLj7KNSB1XV3osgyHIeFsWu3NtaKGzv12Tw93QZmJlb7/8L4hb0Vj8aF/gN7XA8n5bRqxPYIfRADBHlxRI5xnSaqtEIfLuQDbR7MbkxA16E85jr5FNZlYtyXsW6HTAeMNh1WXBv3OvPGBrQ9MTZMWNcwf57kTaM4yH1nTOxnmcgy5oMuNZPs7zxfHKR68h4uN/mRsyblMonL9PZD6ukHOJCLIJ6uun6rWH5zPLiennGK+x6xMGVlnRBGlalPa7JPjyUn9Uli2I+qWsez2n8EijIB0US+lwb6RxI+zcL3Z94RalZ+ovvUr/azOLhDkwZCkP6MT5WjGdoSy7Pf9wrcAPuYpEuzfjXC6/IPKid3Hvi3E=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: gin-vue-2022-06-11t11-36-29
    type: kubernetes.io/dockerconfigjson

