apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-10"
  name: nocalhost-api-sql-init-config
data:
  nocalhost.sql: |-
{{ .Files.Get "sql/nocalhost-api.sql" | indent 4 }}