# Default values for nocalhost-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
api:
  image:
    repository: nocalhost-docker.pkg.coding.net/nocalhost/public/nocalhost-api
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "c803bac73e1e61bd676f26e95fbaccdc034fe18f"
web:
  image:
    repository: nocalhost-docker.pkg.coding.net/nocalhost/public/nocalhost-web
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v0.6.18"
imagePullSecrets: []
podSecurityContext: {}
#  fsGroup: 2000

securityContext: {}
#  capabilities:
#    drop:
#    - ALL
#  readOnlyRootFilesystem: true
#  runAsNonRoot: true
#  runAsUser: 1000

service:
  type: ClusterIP
  port: 80
resources:
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
mariadb:
  fullnameOverride: nocalhost-mariadb
  commonAnnotations: {"helm.sh/hook": "pre-install", "helm.sh/hook-weight": "1"}
  image:
    registry: nocalhost-docker.pkg.coding.net/nocalhost/public
    repository: mariadb
  auth:
    rootPassword: root
    database: nocalhost
  primary:
    persistence:
      size: "10Gi"
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
    extraVolumes:
      - name: nocalhost-api-sql-config-volume
        configMap:
          name: nocalhost-api-sql-init-config
          defaultMode: 0755
    extraVolumeMounts:
      - name: nocalhost-api-sql-config-volume
        mountPath: /docker-entrypoint-initdb.d/
ingress:
  enabled: true
  hosts:
    - nocalhost.h8r.site
  ingressClassName: nginx
